### PR TITLE
add scale_statefulset activity

### PR DESCRIPTION
**Pull request by tdevilleduc**
Signed-off-by: Thomas DEVILLE-DUC <thomas.deville-duc-prestataire@laposte.fr>

### CODE REVIEW

**Comment by Lawouach** [comment]
Looks good, is this replacing one of the oldest PRs? if so, could you close the ones it supersedes please?

**Comment by tdevilleduc** [comment]
> Just lacks a changelog entry :)

Sorry that's my first PRs. I'm on it

**Comment by tdevilleduc** [comment]
> Looks good, is this replacing one of the oldest PRs? if so, could you close the ones it supersedes please?

I cut #68 in two different PRs : 68 and 73. But they both do something.

**Comment by Lawouach** [comment]
did you merge commit or rebase from master? It's surprising to see this commit here 0829553

**Comment by tdevilleduc** [comment]
> did you merge commit or rebase from master? It's surprising to see this commit here [0829553](https://github.com/chaostoolkit/chaostoolkit-kubernetes/commit/0829553d7635c65b95a02b815e48f51e6957329c)

I feel the same. 
I merged master from here to my master branch. Then i rebased my branch with my master
But I don't really understand how to synchronize my fork repo with this one

**Comment by Lawouach** [comment]
Oh I see.

Don't worry, I'm not a git guru either :)

To merge upstream into your master (or actually even directly to your branch).

```
$ git remote add upstream https://github.com/chaostoolkit/chaostoolkit-kubernetes.git
$ git pull --rebase origin upstream
```

The idea is that you configure upstream to point to the master from this repository. Then you pull and rebase directly from upstream master into your branch (without going through your local master).

**Comment by tdevilleduc** [comment]
With your help, i think i manage
I did (not exactly the same) : 
$ git remote add upstream https://github.com/chaostoolkit/chaostoolkit-kubernetes.git
$ git pull --rebase upstream master
$ git push --force

**Comment by Lawouach** [comment]
now, let's pull rebase the next PR :)

**Pull request merged**
