### PR TITLE
Updating kubernetes api version to support the latest `apps/v1` version

### PR DESCRIPTION
**Pull request by r1sharma**
This PR is fix related to the issue #63 & #62 . A part of these issues have been already addressed in Pull request : https://github.com/chaostoolkit/chaostoolkit-kubernetes/pull/53 

Changes include:

- Updated `chaosk8s\actions.py` & `chaosk8s\probes.py`
- Updated related tests too.

### CODE REVIEW

**Comment by r1sharma** [comment]
@Lawouach Sure will update this PR with changeling later today.
Please take a look at the notes [here](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) from Kubernetes on deprecated apis removed from v1.16 and future version of `kubectl`. I am using version 1.16+ for kubectl and chaos toolkit keeps failing for that even after your fix [here](https://github.com/chaostoolkit/chaostoolkit-kubernetes/pull/53) as current code points to `apps/v1beta1`.

**Comment by Lawouach** [comment]
Makes sense and your fix seems the right one. Wondering about backward compatibility.

**Comment by rahulsharma-cbre** [comment]
previous version of `chaosk8s` will be compatible. right?

**Comment by r1sharma** [comment]
previous version of `chaosk8s` will be compatible. right?

**Comment by Lawouach** [comment]
True although this isn't my philosophy here. But, reading your link again, they mention the `apps/v1` version has been around since K8S 1.9 which is "old" (with Kubernetes, 18 months is ancient times).

I might work on a change, after yours, that will try to support both by looking up the version of the server first.

**Comment by r1sharma** [comment]
Sounds good

**Pull request merged**
