### PR TITLE
Fix small display log typo

### PR DESCRIPTION
**Pull request by dviniere**
A small issue in logs where deployments replaces replicas set in the display string

### CODE REVIEW

**Comment by Lawouach** [comment]
Hey @dviniere,

Thanks for being responsive on the DCO, that's helpful :)

I'm wondering what happened with the merge commit 6e0c30a? Did you rebase or merge and comitted? Just want to ensure the tree stays clean :)

**Comment by dviniere** [comment]
Hi,
 I tried to amend my commit with the DCO, but I may have done something wrong as it caused a merge as you can see with the previous commit and a new one with the amended line.
I'm not used to git yet so I tried to use the Github Desktop, might have miss something x)

**Comment by Lawouach** [comment]
I see! 

Well, it takes a while to get there for sure (git isn't straightforward ;)).

Let me look at the tree.

**Comment by Lawouach** [comment]
I squashed from here and picked the only commit that really was relevant!

Thank you for catching that one by the way.

And welcome! :)

**Comment by dviniere** [comment]
You're welcome.
For next time I'll remember to add the DCO directly to avoid this mess :D 

Glad to be able to help, even if it was not that big, and thank you for your great toolkit ;)

**Comment by Lawouach** [comment]
A tip, if you have configured your .gitconfig properly (name and email), you can just add the `-s` flag to your `git commit` and the signature will be added automatically :)

**Pull request merged**
